from __future__ import annotations


SAMPLE_POSTINGS = [
    {
        "source": "sample",
        "posting_id": "SAMPLE-001",
        "company": "데이터브릿지",
        "title": "신입 데이터 분석가 채용",
        "description": "SQL과 Python을 활용한 매출 데이터 분석, Tableau 대시보드 운영, A/B Test 결과 리포팅",
        "region": "서울 강남구",
        "career": "신입",
        "education": "대졸(4년)",
        "salary_type": "연봉",
        "salary": "회사내규",
        "job_code": "134",
        "registered_at": "2026-05-20",
        "closing_at": "2026-06-20",
        "url": "https://example.com/jobs/sample-001",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-002",
        "company": "커머스인사이트",
        "title": "BI 분석가 모집",
        "description": "Power BI, SQL, Excel 기반 KPI 대시보드 제작 및 경영진 리포트 자동화",
        "region": "서울 마포구",
        "career": "경력",
        "education": "학력무관",
        "salary_type": "연봉",
        "salary": "4000만원 이상",
        "job_code": "134",
        "registered_at": "2026-05-18",
        "closing_at": "2026-06-15",
        "url": "https://example.com/jobs/sample-002",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-003",
        "company": "로그파이프",
        "title": "데이터 엔지니어",
        "description": "Spark, Airflow, Kafka 기반 데이터 파이프라인 개발. AWS와 PostgreSQL 운영 경험 우대",
        "region": "경기 성남시",
        "career": "경력",
        "education": "대졸(4년)",
        "salary_type": "연봉",
        "salary": "면접 후 결정",
        "job_code": "133",
        "registered_at": "2026-05-21",
        "closing_at": "2026-06-25",
        "url": "https://example.com/jobs/sample-003",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-004",
        "company": "에듀AI",
        "title": "머신러닝 엔지니어 채용",
        "description": "Python, PyTorch, TensorFlow를 활용한 추천 모델 개발. NLP 프로젝트 경험 우대",
        "region": "서울 서초구",
        "career": "경력",
        "education": "석사",
        "salary_type": "연봉",
        "salary": "5000만원 이상",
        "job_code": "133",
        "registered_at": "2026-05-22",
        "closing_at": "2026-06-30",
        "url": "https://example.com/jobs/sample-004",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-005",
        "company": "핀테크랩",
        "title": "데이터 분석 인턴",
        "description": "Pandas, NumPy, SQL을 활용한 금융 데이터 전처리 및 통계 분석 보조",
        "region": "서울 영등포구",
        "career": "신입",
        "education": "학력무관",
        "salary_type": "월급",
        "salary": "220만원",
        "job_code": "134",
        "registered_at": "2026-05-17",
        "closing_at": "2026-06-10",
        "url": "https://example.com/jobs/sample-005",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-006",
        "company": "리테일옵스",
        "title": "CRM 데이터 분석가",
        "description": "고객 세그먼트 분석, SQL 쿼리 작성, Python 리포트 자동화, Looker 대시보드 관리",
        "region": "부산 해운대구",
        "career": "무관",
        "education": "대졸(2~3년)",
        "salary_type": "연봉",
        "salary": "회사내규",
        "job_code": "134",
        "registered_at": "2026-05-16",
        "closing_at": "2026-06-12",
        "url": "https://example.com/jobs/sample-006",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-007",
        "company": "클라우드메트릭",
        "title": "데이터 플랫폼 엔지니어",
        "description": "Docker, Kubernetes, AWS, MySQL, Airflow 기반 배치 파이프라인 구축",
        "region": "경기 판교",
        "career": "경력",
        "education": "학력무관",
        "salary_type": "연봉",
        "salary": "면접 후 결정",
        "job_code": "133",
        "registered_at": "2026-05-23",
        "closing_at": "2026-07-01",
        "url": "https://example.com/jobs/sample-007",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-008",
        "company": "헬스데이터",
        "title": "AI 데이터 사이언티스트",
        "description": "Machine Learning, Deep Learning, Statistics, Python 기반 의료 데이터 모델링",
        "region": "대전 유성구",
        "career": "경력",
        "education": "석사",
        "salary_type": "연봉",
        "salary": "회사내규",
        "job_code": "133",
        "registered_at": "2026-05-19",
        "closing_at": "2026-06-28",
        "url": "https://example.com/jobs/sample-008",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-009",
        "company": "제조데이터웍스",
        "title": "스마트팩토리 데이터 분석 담당자",
        "description": "R, Python, SQL을 활용한 생산 데이터 분석. Power BI 시각화 경험 우대",
        "region": "경남 창원시",
        "career": "무관",
        "education": "대졸(4년)",
        "salary_type": "연봉",
        "salary": "3500만원 이상",
        "job_code": "134",
        "registered_at": "2026-05-14",
        "closing_at": "2026-06-14",
        "url": "https://example.com/jobs/sample-009",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-010",
        "company": "마케팅그로스",
        "title": "그로스 데이터 분석가",
        "description": "GA4, SQL, Python, A/B Test 기반 퍼널 분석 및 캠페인 성과 개선",
        "region": "서울 종로구",
        "career": "신입",
        "education": "학력무관",
        "salary_type": "연봉",
        "salary": "회사내규",
        "job_code": "134",
        "registered_at": "2026-05-25",
        "closing_at": "2026-06-23",
        "url": "https://example.com/jobs/sample-010",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-011",
        "company": "모빌리티AI",
        "title": "NLP/추천시스템 ML 엔지니어",
        "description": "NLP, Recommender System, PyTorch, Python, Docker 기반 모델 서빙",
        "region": "서울 성동구",
        "career": "경력",
        "education": "대졸(4년)",
        "salary_type": "연봉",
        "salary": "면접 후 결정",
        "job_code": "133",
        "registered_at": "2026-05-24",
        "closing_at": "2026-06-29",
        "url": "https://example.com/jobs/sample-011",
    },
    {
        "source": "sample",
        "posting_id": "SAMPLE-012",
        "company": "공공데이터센터",
        "title": "공공데이터 분석 및 시각화 담당",
        "description": "PostgreSQL, Python, Plotly, Tableau를 활용한 공공데이터 분석 보고서 작성",
        "region": "세종",
        "career": "무관",
        "education": "대졸(4년)",
        "salary_type": "연봉",
        "salary": "회사내규",
        "job_code": "134",
        "registered_at": "2026-05-13",
        "closing_at": "2026-06-18",
        "url": "https://example.com/jobs/sample-012",
    },
]
